server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalog-route
              uri: http://catalog-service:8081
              predicates:
                - Path=/api/v1/catalog/**
              filters:
                - RewritePath=/api/v1/catalog/(?<segment>.*), /api/v1/$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG